apiVersion: v2
name: spark-operator
description: A Helm chart for Spark on Kubernetes operator.
version: 2.0.5
appVersion: 2.0.2
keywords:
- apache spark
- big data
home: https://github.com/kubeflow/spark-operator
maintainers:
- name: yuchaoran2011
  email: yuchaoran2011@gmail.com
  url: https://github.com/yuchaoran2011
- name: ChenYi015
  email: github@chenyicn.net
  url: https://github.com/ChenYi015
